"""empty message

Revision ID: 9ffb62e6d51d
Revises: 127134ccfddd
Create Date: 2024-01-12 11:39:34.502598

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ffb62e6d51d'
down_revision = '127134ccfddd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userId', sa.Integer(), nullable=False),
    sa.Column('shopId', sa.Integer(), nullable=True),
    sa.Column('shopName', sa.String(), nullable=True),
    sa.Column('orderStatus', sa.String(), nullable=False),
    sa.Column('orderType', sa.String(), nullable=True),
    sa.Column('purchasedAt', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['shopId'], ['shops.id'], ),
    sa.ForeignKeyConstraint(['userId'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('order_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('orderId', sa.Integer(), nullable=False),
    sa.Column('critterId', sa.Integer(), nullable=False),
    sa.Column('critterName', sa.String(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unitPrice', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['critterId'], ['critters.id'], ),
    sa.ForeignKeyConstraint(['orderId'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order_details')
    op.drop_table('orders')
    # ### end Alembic commands ###